### ISSUE TITLE
Don't use Issuehunt

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/meetings#20]
Hi Everyone,

Today I received an email stating Issuehunt is being added to Sequelize project. I know I have left the project but this was important so I am posting this here. I don't think Sequelize should add Issuehunt.

Why?

- They don't have an automated way to withdraw your funds. Withdrawal emails (or any other emails) are usually ignored.
- You need to earn at-least $100 USD to withdraw.
- As a project owner, you can't get funds stuck in stale issues. If there is a bounty on an issue, it can't be utilized for something else.

Idea of bounties is great but these platforms are shady at best. I don't want contributors money get stuck in some third party platform.

Thanks!

**Comment by ephys** [comment]
Hey @sushantdhiman, nice to see you 👋

We came to the same conclusion and removed it a few minutes later. The platform just did not feel safe enough to entrust them with anyone's money.

If we ever set up an issue bounty, it'll be through a platform we can trust. It'd be nice if open collective released such a feature

**Comment by ephys** [comment]
I'll close as, well, it's solved :)
