### ISSUE TITLE
Prettier?

### ISSUE THREAD

**Issue by ephys** [sequelize/meetings#32]
I've usually been opposed to `prettier` because it does not allow me to decide on the code style as much as I'd like, but I have to admit that the output generated by prettier has improved over the years.

Considering that our eslint preset can be _very_ slow on some files (i even upgraded my setup with this as one of the reasons), and that prettier is _very_ fast. I think we could consider replacing all stylistic eslint rules that prettier handles with prettier, and keeping eslint for bug detection & elements that prettier does not handle yet.

Oh, and `prettier-plugin-organize-imports` automatically removes unused imports on format
```[tasklist]
### Tasks
- [ ] https://github.com/sequelize/sequelize/pull/17101
- [ ] https://github.com/sequelize/website/pull/745
```

**Comment by WikiRik** [comment]
I think this is also the way eslint is going; https://eslint.org/blog/2023/10/deprecating-formatting-rules/

**Comment by ephys** [comment]
Ah, well we won't even have a choice so I'll look into opening a PR for that then
