### ISSUE TITLE
Which versions of Node.JS do we want to support?

### ISSUE THREAD

**Issue by sdepold** [sequelize/meetings#5]

**Comment by sdepold** [comment]
Related: https://github.com/sequelize/sequelize/pull/13634

**Comment by fncolon** [comment]
Look like > Active LTS is nice choice to be supported.

LTS version will be further supported by the Open JS foundation for a long time [see here](https://nodejs.org/en/about/releases/)

**Comment by WikiRik** [comment]
I would support all LTS versions, so both active and maintenance. I would not support current versions of Node since changes to those might not be persisting.

**Comment by sdepold** [comment]
It arose in the CLI since support for modules was supported.

Pedro: 
Support all version that are officially support by the Node org.
However, if we remove support for particular version, it is a breaking change hence it should be a major release.
Do we want to release major version however, whenever Node version is deprecated?

Sascha: Could we just increase the supported node version in the package.json?

Pedro: It will result in a warning. npm/yarn is not preventing installation.

Gregory: At least yarn will prevent installing it that way.

Jesse: npm will install it nevertheless.

Sascha: Anybody against a major version release?

Constantin: Let's just let it sit in the back until we have enough reasons to do a major version bump.

Pedro: New features in Node 12 such as Array#flat will break in other versions. If major version release are easy to be upgraded to, it is fine to do it.

**Consensus: Dropping support for Node 10 should imply a Major version update.**

Q: When should we drop support for Node 10?

Maybe: Wrap up the TypeScript migration and only then drop support for Node 10 + major version upgrade?

Pedro: Let's add more breaking changes along with it.

**Comment by sdepold** [comment]
--> #2

**Comment by sdepold** [comment]
Rik: I do think this also goes hand in hand with which versions of Sequelize the CLI supports. Currently it's v5 and latest, but it might be good to only support the latest major version and have the same Node requirements there

**Comment by sdepold** [comment]
Pedro: Community dislikes breaking changes

**Comment by WikiRik** [comment]
@sdepold shall we reopen it to do the follow up at the next meeting?

**Comment by sdepold** [comment]
Sounds good :)

**Comment by sdepold** [comment]
However I thought the consensus was that we accumulated enough breaking changes and upgrade to lts then?

**Comment by WikiRik** [comment]
That's true, not sure though why we didn't close it directly. Maybe to give people some extra time to respond?
